version: '3'

services:
  database:
    image: 'mysql/mysql-server:8.0'
    container_name: apiflask-database
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: "apiflask"
      MYSQL_ROOT_HOST: "%"
      MYSQL_USER: "docker"
      MYSQL_ROOT_PASSWORD: "1NfHJ9WK*X2<YI`Z%"
      MYSQL_PASSWORD: "NfHJ9WK*X2<YI`Z%"
      MYSQL_ALLOW_EMPTY_PASSWORD: "1"
    volumes:
      - 'mysql_data:/var/lib/mysql'
    networks:
      - apiflaskServerNetwork
volumes:
  mysql_data:
    driver: local
networks:
  apiflaskServerNetwork:
    driver: bridge
