"""empty message

Revision ID: 115311d4d63e
Revises: 323284e73d61
Create Date: 2023-11-01 09:26:08.917913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '115311d4d63e'
down_revision = '323284e73d61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('formations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('formations')
    # ### end Alembic commands ###
