"""empty message

Revision ID: 4710d8691719
Revises: 115311d4d63e
Create Date: 2023-11-01 09:59:43.611682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4710d8691719'
down_revision = '115311d4d63e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('formation_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'formations', ['formation_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('formation_id')

    # ### end Alembic commands ###
