"""empty message

Revision ID: 505cfdba95d5
Revises: 6baccf7a9075
Create Date: 2023-12-03 00:31:15.809151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '505cfdba95d5'
down_revision = '6baccf7a9075'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
