"""empty message

Revision ID: 719f1484ec56
Revises: fbbfedf2a8a2
Create Date: 2023-12-03 22:06:35.630910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '719f1484ec56'
down_revision = 'fbbfedf2a8a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_key', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('api_key')

    # ### end Alembic commands ###
